# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_full',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
