# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170704_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_full',
            field=models.TextField(),
        ),
    ]
